### ISSUE TITLE
Usability questions

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/brand-icon-browser#2]
Here are a few usability issues that I picked up on. They may not all be useful, but keeping them in mine is probably a good thing.

- First page load is jittery,[ should we be offering grey boxes on load like youtube, facebook, or storybook?](https://stackoverflow.com/questions/49962206/how-to-do-what-youtube-does-with-the-grey-boxes-while-loading)
    -  https://github.com/uiowa/brand-icon-browser/issues/14
- are the bottom two icons (Yellow lined and white lined supposed to be png only?)
    - https://github.com/uiowa/brand-icon-browser/issues/15
- Could we benefit from having a confirmation dialogue for the "Download all" button? I accidentally clicked it since it was so close to the one and two color, and before I knew it i had a million icons on my computer.
- Do we need the icon indexes in the downloads of all icons?
    - https://github.com/uiowa/brand-icons/issues/14
- There is some color lag with changing from two color to one color and vice versa, should we "greybox" this as well?
    - https://github.com/uiowa/brand-icon-browser/issues/16

**Comment by quamsta** [comment]
> First page load is jittery,[ should we be offering grey boxes on load like youtube, facebook, or storybook?](https://stackoverflow.com/questions/49962206/how-to-do-what-youtube-does-with-the-grey-boxes-while-loading)

Yes! I don't know how to do this though. Hah.

> Could we benefit from having a confirmation dialogue for the "Download all" button? I accidentally clicked it since it was so close to the one and two color, and before I knew it i had a million icons on my computer.

I think moving the download button as per @bspeare's suggestion in https://github.com/uiowa/brand-icon-browser/issues/1#issue-1235398454 might help with this. I'm hesitant to throw up an interstitial modal or something just for this.

> Do we need the icon indexes in the downloads of all icons?

I personally don't think so once the browser has been launched, especially if the PDFs fall out of date if more icons are added, but right now I'm linking to the [`brand-icons` repo'](https://github.com/uiowa/brand-icon-browse)'s GitHub download link, which contains those files. Probably another issue for that repo.

> There is some color lag with changing from two color to one color and vice versa, should we "greybox" this as well?

Possibly, although possibly introducing pagination  or "load as you scroll" so that fewer DOM elements aren't changing at once may alleviate this. (500 or so icons are changing their variants at once, which may be hard on the CPU)  I'm a little hesitant to run any code in between the color switch, just for performance reasons.

**Comment by GaryRidgway** [comment]
Perhamp this is helpful?
https://learnvue.co/2020/04/vue-skeleton-loading-screen-using-suspense-components-daily-vue-4/#how-is-our-skeleton-loading-screen-going-to-work

**Comment by GaryRidgway** [comment]
Capturing from our meeting today:

When pressing search with an empty search bar, it should query all icons. Currently, if you search a subset of icons and then clear the search bar and then try and press search again with an empty search bar it will not update the results.

**Comment by quamsta** [comment]
> Capturing from our meeting today:
> 
> When pressing search with an empty search bar, it should query all icons. Currently, if you search a subset of icons and then clear the search bar and then try and press search again with an empty search bar it will not update the results.

This has been resolved in https://github.com/uiowa/brand-icon-browser/commit/086ef02687cccf4123296d04c172926113b593d1

Thanks @GaryRidgway !! :)

**Comment by GaryRidgway** [comment]
I can get some PRs created, no worries!

**Comment by GaryRidgway** [comment]
@quamsta Issues for the ones you were hoping for have been created!

**Comment by joewhitsitt** [comment]
Late to the discussion. Checked it out today. Looking awesome. Not going to lie though, I tried to close the modal without paying attention and realized the X was in the upper-left instead of the traditional upper-right.

**Comment by quamsta** [comment]
@joewhitsitt That's a good point. It looks like the image gallery in SiteNow and even the AIS component modals are using top right. I think this is a good idea.

**Comment by quamsta** [comment]
Closing these out for now, since the only outstanding item being discussed has its own issue: https://github.com/uiowa/brand-icon-browser/issues/16
